[package]
name = "hello-world-rust-lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.8.2"
serde_json = "1.0.107"
tokio = "1.32.0"